version: "3.9"

services:
  wallet:
    container_name: wallet
    image: gitlab-registry.ozon.dev/qa/classroom-14/students/service/wallet:master
    environment:
      PG_DSN: "host=postgres port=5432 dbname=wallet user=postgres password=postgres sslmode=disable"
    ports:
      - "8002:8002" # gRPC
      - "8001:8001" # REST
      - "9100:9100" # Metrics prometheus
      - "8000:8000" # Status prometheus
    healthcheck:
      test: [ 'CMD', 'curl', '-v', 'http://localhost:8000/live' ]
      interval: 10s
      timeout: 10s
      retries: 2
      start_period: 20s
    networks:
      - ompnw
    depends_on:
      - postgres
      - pgboucer

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - ompnw
    depends_on:
      - wallet
      - swagger-ui

  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui:v4.10.3
    restart: always
    volumes:
      - ./pkg/swagger:/swagger
    environment:
      SWAGGER_JSON: /swagger/wallet/wallet.swagger.json
    networks:
      - ompnw
    depends_on:
      - wallet

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    networks:
      - ompnw
    ports:
      - "22181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    networks:
      - ompnw
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallet
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - ompnw

  pgboucer:
    container_name: pgboucer
    image: edoburu/pgbouncer
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_NAME: wallet
      MAX_CLIENT_CONN: 100
      MAX_USER_CONNECTIONS: 20
      MAX_DB_CONNECTIONS: 20
      DEFAULT_POOL_SIZE: 20
    ports:
      - "6432:5432"
    networks:
      - ompnw
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local

networks:
  ompnw:
    driver: bridge
