{
 "title": "Wallet",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job='wallet'},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Мониторинг GO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RPS & Response Time by Handler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "instance",
   "collapsed": true
  },
  {
   "title": "RPS by Handler",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{instance=~\"$instance\"}[1m])) by (grpc_method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time by Handler",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket{instance=~\"$instance\"}[5m])) by (le, grpc_method))",
     "legendFormat": "q50 {{grpc_method}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_server_handling_seconds_bucket{instance=~\"$instance\"}[5m])) by (le, grpc_method))",
     "legendFormat": "q90 {{grpc_method}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{instance=~\"$instance\"}[5m])) by (le, grpc_method))",
     "legendFormat": "q99 {{grpc_method}}"
    }
   ]
  },
  {
   "title": "RPS by Code",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{instance=~\"$instance\"}[1m])) by (grpc_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS and Response Time Percentiles by Instance",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{instance=~'$instance'}[1m])) by (instance)",
     "legendFormat": "RPS"
    },
    {
     "expr": "quantile(0.5, rate(grpc_server_handling_seconds_sum{instance=~'$instance'}[1m]>=0)) by (instance)",
     "legendFormat": "q50"
    },
    {
     "expr": "quantile(0.9, rate(grpc_server_handling_seconds_sum{instance=~'$instance'}[1m]>=0)) by (instance)",
     "legendFormat": "q90"
    },
    {
     "expr": "quantile(0.99, rate(grpc_server_handling_seconds_sum{instance=~'$instance'}[1m]>=0)) by (instance)",
     "legendFormat": "q99"
    }
   ]
  }
 ]
}