{
 "title": "Yandex-tank",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "label",
    "query": {
     "query": "label_values(overall_quantiles,label)"
    }
   },
   {
    "name": "tank",
    "query": {
     "query": "label_values(overall_quantiles,tank)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Results $label", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "label" },
  {
   "title": "Meta Information",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(overall_meta{label=~\"$label\",tank=\"$tank\"}[1m]) by (field)",
     "legendFormat": "{{field}}"
    }
   ]
  },
  {
   "title": "Net/Proto Codes",
   "type": "timeseries",
   "description": "Net и Proto - коды - служат для определения сбоев в пушке/ проблем с сетевыми подключениями и так далее.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg(net_codes{label=~\"$label\",tank=\"$tank\"}[1m]) by (field_label)",
     "legendFormat": "Net - {{field_label}}"
    },
    {
     "expr": "avg(proto_codes{label=~\"$label\",tank=\"$tank\"}[1m]) by (field_label)",
     "legendFormat": "Proto - {{field_label}}"
    }
   ]
  },
  {
   "title": "Распределение времен отклика",
   "type": "timeseries",
   "description": "График времен отклика - (100, 98, 50 квантили)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(overall_quantiles{field=~'q100|q98|q90|q50',label=~\"$label\",tank=\"$tank\"}) by (field)",
     "legendFormat": "{{field}}"
    },
    {
     "expr": "avg(overall_meta{label=~\"$label\",field=\"RPS\",tank=\"$tank\"}) by(field)",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Распределение Времен отклика",
   "type": "histogram",
   "description": "Гистограмма распределения времен отклика.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histograms{label=~\"$label\", field=\"bin\",tank=\"$tank\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}