version: "3.9"

services:
  mongodb:
    image: "mongo:5.0"
    volumes:
      - "mongodb_data:/data/db"
    restart: "on-failure"

  opensearch:
    image: "opensearchproject/opensearch:2.4.0"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "os_data:/usr/share/opensearch/data"
    restart: "on-failure"

  graylog:
    hostname: "server"
    image: "${GRAYLOG_IMAGE:-graylog/graylog:5.0}"
    depends_on:
      opensearch:
        condition: "service_started"
      mongodb:
        condition: "service_started"
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9001/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
      - "5044:5044/tcp"
      - "5140:5140/udp"
      - "5140:5140/tcp"
      - "5555:5555/tcp"
      - "5555:5555/udp"
      - "9001:9000/tcp"
      - "12201:12201/tcp"
      - "12201:12201/udp" # GELF UDP
      #- "10000:10000/tcp"
      #- "10000:10000/udp" # Custom
      - "13301:13301/tcp"
      - "13302:13302/tcp"
    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
      - "graylog_journal:/usr/share/graylog/data/journal"
    restart: "on-failure"

  victoria:
    container_name: victoria-metrics
    image: victoriametrics/victoria-metrics
    restart: always
    volumes:
      - ./docker/victoria:/victoria-metrics-data
      - ./prometheus.yml:/prometheus.yml
    command:
      - -opentsdbHTTPListenAddr=:4242
      - -influxListenAddr=:8089
      - -promscrape.config=/prometheus.yml
    ports:
      - "8428:8428"
      - "4242:4242"
      - "8089:8089/tcp"
      - "8089:8089/udp"
    networks:
      - ompnw

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: root
    volumes:
      - ./docker/grafana/data:/var/lib/grafana/
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: "grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    ports:
      - "3000:3000"
    networks:
      - ompnw

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    expose:
      - 9100
    networks:
      - ompnw

  postgres-exporter:
    image: wrouesnel/postgres_exporter:latest
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/wallet?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - ompnw

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    ports:
      - "9308:9308"
    environment:
      KAFKA_SERVER: kafka:9092
    networks:
      - ompnw
    depends_on:
      - kafka

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8085:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    networks:
      - ompnw

volumes:
  mongodb_data:
  os_data:
  graylog_data:
  graylog_journal:

networks:
  ompnw:
    driver: bridge
