global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "victoria"
    static_configs:
      - targets:
          - localhost:8428

  - job_name: node_exporter
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: wallet
    static_configs:
      - targets: ["wallet:9100"]

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
